import React from "react";

export const metadata = {
  title: "Contact  ",
  description: "Generated by monir",
};

const Contact = () => {
  return (
    <div className=" bg-lime-300  ">
      <h1>Contact us </h1>
      <h1>Contact us </h1>
      <h1>Contact us </h1>
      <h1>Contact us </h1>
      <h1>Contact us </h1>
    </div>
  );
};

export default Contact;
