import React from "react";

import AboutImg from "@/public/about.jpg";
import Image from "next/image";

export const metadata = {
  title: "About  ",
  description: "Generated by monir",
};

const About = () => {
  return (
    <div className=" bg-red-300 ">
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>

      <div className="bannerImage bg-red-500 w-[30rem]  mt-4 ">
        <Image src={AboutImg} alt="banner pic " />
      </div>
    </div>
  );
};

export default About;
