import React from "react";

export const metadata = {
  title: "About  ",
  description: "Generated by monir",
};

const About = () => {
  return (
    <div className=" bg-red-300 ">
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
    </div>
  );
};

export default About;
