import React from "react";

import AboutImg from "@/public/about.jpg";
import Image from "next/image";

export const metadata = {
  title: "About  ",
  description: "Generated by monir",
};

const About = () => {
  throw new Error("there is a error");
  return (
    <div className=" bg-red-300 ">
      <h1 className=" " >About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1>About page </h1>
      <h1> added from code space    </h1>
      <h1> added from code space    </h1>
      <h1> added from code space    </h1>
      <h1> added from code space    </h1>
      

      <div className="bannerImage BlogValues w-[30rem]  mt-4 ">
        <Image src={AboutImg} alt="banner pic " placeholder="blur" />
      </div>
    </div>
  );
};

export default About;
