import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js learning",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* navbar starts  */}
        <nav className=" bg-red-50 py-4 px-2 ">
          <ul className=" flex gap-3 text-2xl  ">
            <Link href={`/`}>home </Link>
            <Link href={`/contact`}>contact</Link>
            <Link href={`/about`}>about</Link>
            <Link href={`/blogs`}>blog</Link>
          </ul>
        </nav>
        {/* navbar ends  */}

        {children}
      </body>
    </html>
  );
}
